CvssMetringScorings.delete_all

        CvssMetringScorings.create([{metric_name: 'AccessComplexity', abrv_metric_name: 'AC', metric_value: 'High', abvr_metric_value: 'High', numeric_value: '0.35'}])
        CvssMetringScorings.create([{metric_name: 'AccessComplexity', abrv_metric_name: 'AC', metric_value: 'Medium', abvr_metric_value: 'M', numeric_value: '0.61'}])
        CvssMetringScorings.create([{metric_name: 'AccessComplexity', abrv_metric_name: 'AC', metric_value: 'Low', abvr_metric_value: 'L', numeric_value: '0.71'}])
        CvssMetringScorings.create([{metric_name: 'AccessVector', abrv_metric_name: 'AV', metric_value: 'Local', abvr_metric_value: 'L', numeric_value: '0.395'}])
        CvssMetringScorings.create([{metric_name: 'AccessVector', abrv_metric_name: 'AV', metric_value: 'Adjacent Network', abvr_metric_value: 'A', numeric_value: '0.646'}])
        CvssMetringScorings.create([{metric_name: 'AccessVector', abrv_metric_name: 'AV', metric_value: 'Network', abvr_metric_value: 'N', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'Authentication', abrv_metric_name: 'Au', metric_value: 'None', abvr_metric_value: 'N', numeric_value: '0.704'}])
        CvssMetringScorings.create([{metric_name: 'Authentication', abrv_metric_name: 'Au', metric_value: 'Single Instance', abvr_metric_value: 'S', numeric_value: '0.56'}])
        CvssMetringScorings.create([{metric_name: 'Authentication', abrv_metric_name: 'Au', metric_value: 'Multiple Instance', abvr_metric_value: 'M', numeric_value: '0.45'}])
        CvssMetringScorings.create([{metric_name: 'AvailabilityRequirement', abrv_metric_name: 'AR', metric_value: 'Undefined', abvr_metric_value: 'ND', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'AvailabilityRequirement', abrv_metric_name: 'AR', metric_value: 'Low', abvr_metric_value: 'L', numeric_value: '0.5'}])
        CvssMetringScorings.create([{metric_name: 'AvailabilityRequirement', abrv_metric_name: 'AR', metric_value: 'Medium', abvr_metric_value: 'M', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'AvailabilityRequirement', abrv_metric_name: 'AR', metric_value: 'High', abvr_metric_value: 'H', numeric_value: '1.51'}])
        CvssMetringScorings.create([{metric_name: 'AvailImpact', abrv_metric_name: 'A', metric_value: 'None', abvr_metric_value: 'N', numeric_value: '0'}])
        CvssMetringScorings.create([{metric_name: 'AvailImpact', abrv_metric_name: 'A', metric_value: 'Partial', abvr_metric_value: 'P', numeric_value: '0.275'}])
        CvssMetringScorings.create([{metric_name: 'AvailImpact', abrv_metric_name: 'A', metric_value: 'Complete', abvr_metric_value: 'C', numeric_value: '0.66'}])
        CvssMetringScorings.create([{metric_name: 'CollateralDamagePotential', abrv_metric_name: 'CDP', metric_value: 'Undefined', abvr_metric_value: 'ND', numeric_value: '0'}])
        CvssMetringScorings.create([{metric_name: 'CollateralDamagePotential', abrv_metric_name: 'CDP', metric_value: 'None', abvr_metric_value: 'N', numeric_value: '0'}])
        CvssMetringScorings.create([{metric_name: 'CollateralDamagePotential', abrv_metric_name: 'CDP', metric_value: 'Low(light loss)', abvr_metric_value: 'L', numeric_value: '0.1'}])
        CvssMetringScorings.create([{metric_name: 'CollateralDamagePotential', abrv_metric_name: 'CDP', metric_value: 'Low-Medium', abvr_metric_value: 'LM', numeric_value: '0.3'}])
        CvssMetringScorings.create([{metric_name: 'CollateralDamagePotential', abrv_metric_name: 'CDP', metric_value: 'Medium-High', abvr_metric_value: 'MH', numeric_value: '0.4'}])
        CvssMetringScorings.create([{metric_name: 'CollateralDamagePotential', abrv_metric_name: 'CDP', metric_value: 'High', abvr_metric_value: 'H', numeric_value: '0.5'}])
        CvssMetringScorings.create([{metric_name: 'ConfidentialityRequirement', abrv_metric_name: 'CR', metric_value: 'Undefined', abvr_metric_value: 'ND', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'ConfidentialityRequirement', abrv_metric_name: 'CR', metric_value: 'Low', abvr_metric_value: 'L', numeric_value: '0.5'}])
        CvssMetringScorings.create([{metric_name: 'ConfidentialityRequirement', abrv_metric_name: 'CR', metric_value: 'Medium', abvr_metric_value: 'M', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'ConfidentialityRequirement', abrv_metric_name: 'CR', metric_value: 'High', abvr_metric_value: 'H', numeric_value: '1.51'}])
        CvssMetringScorings.create([{metric_name: 'ConfImpact', abrv_metric_name: 'C', metric_value: 'None', abvr_metric_value: 'N', numeric_value: '0'}])
        CvssMetringScorings.create([{metric_name: 'ConfImpact', abrv_metric_name: 'C', metric_value: 'Partial', abvr_metric_value: 'P', numeric_value: '0.275'}])
        CvssMetringScorings.create([{metric_name: 'ConfImpact', abrv_metric_name: 'C', metric_value: 'Complete', abvr_metric_value: 'C', numeric_value: '0.66'}])
        CvssMetringScorings.create([{metric_name: 'Exploitability', abrv_metric_name: 'E', metric_value: 'Undefined', abvr_metric_value: 'ND', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'Exploitability', abrv_metric_name: 'E', metric_value: 'Unproven that expolit exists', abvr_metric_value: 'U', numeric_value: '0.85'}])
        CvssMetringScorings.create([{metric_name: 'Exploitability', abrv_metric_name: 'E', metric_value: 'Proof of concept code', abvr_metric_value: 'POC', numeric_value: '0.9'}])
        CvssMetringScorings.create([{metric_name: 'Exploitability', abrv_metric_name: 'E', metric_value: 'Functional expolit exists', abvr_metric_value: 'F', numeric_value: '0.95'}])
        CvssMetringScorings.create([{metric_name: 'Exploitability', abrv_metric_name: 'E', metric_value: 'Widespread', abvr_metric_value: 'H', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'IntegImpact', abrv_metric_name: 'I', metric_value: 'None', abvr_metric_value: 'N', numeric_value: '0'}])
        CvssMetringScorings.create([{metric_name: 'IntegImpact', abrv_metric_name: 'I', metric_value: 'Partial', abvr_metric_value: 'P', numeric_value: '0.275'}])
        CvssMetringScorings.create([{metric_name: 'IntegImpact', abrv_metric_name: 'I', metric_value: 'Complete', abvr_metric_value: 'C', numeric_value: '0.66'}])
        CvssMetringScorings.create([{metric_name: 'IntegrityRequirement', abrv_metric_name: 'IR', metric_value: 'Undefined', abvr_metric_value: 'ND', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'IntegrityRequirement', abrv_metric_name: 'IR', metric_value: 'Low', abvr_metric_value: 'L', numeric_value: '0.5'}])
        CvssMetringScorings.create([{metric_name: 'IntegrityRequirement', abrv_metric_name: 'IR', metric_value: 'Medium', abvr_metric_value: 'M', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'IntegrityRequirement', abrv_metric_name: 'IR', metric_value: 'High', abvr_metric_value: 'H', numeric_value: '1.51'}])
        CvssMetringScorings.create([{metric_name: 'RemediationLevel', abrv_metric_name: 'RL', metric_value: 'Undefined', abvr_metric_value: 'ND', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'RemediationLevel', abrv_metric_name: 'RL', metric_value: 'Official fix', abvr_metric_value: 'OF', numeric_value: '0.87'}])
        CvssMetringScorings.create([{metric_name: 'RemediationLevel', abrv_metric_name: 'RL', metric_value: 'Temporary fix', abvr_metric_value: 'TF', numeric_value: '0.9'}])
        CvssMetringScorings.create([{metric_name: 'RemediationLevel', abrv_metric_name: 'RL', metric_value: 'Workaround', abvr_metric_value: 'W', numeric_value: '0.95'}])
        CvssMetringScorings.create([{metric_name: 'RemediationLevel', abrv_metric_name: 'RL', metric_value: 'Unavailable', abvr_metric_value: 'U', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'ReportConfidence', abrv_metric_name: 'RC', metric_value: 'Undefined', abvr_metric_value: 'ND', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'ReportConfidence', abrv_metric_name: 'RC', metric_value: 'Unconfirmed', abvr_metric_value: 'UC', numeric_value: '0.9'}])
        CvssMetringScorings.create([{metric_name: 'ReportConfidence', abrv_metric_name: 'RC', metric_value: 'Uncorroborated', abvr_metric_value: 'UR', numeric_value: '0.95'}])
        CvssMetringScorings.create([{metric_name: 'ReportConfidence', abrv_metric_name: 'RC', metric_value: 'Confirmed', abvr_metric_value: 'C', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'TargetDistribution', abrv_metric_name: 'TD', metric_value: 'Undefined', abvr_metric_value: 'ND', numeric_value: '1'}])
        CvssMetringScorings.create([{metric_name: 'TargetDistribution', abrv_metric_name: 'TD', metric_value: 'None (0%)', abvr_metric_value: 'N', numeric_value: '0'}])
        CvssMetringScorings.create([{metric_name: 'TargetDistribution', abrv_metric_name: 'TD', metric_value: 'Low (0-25%)', abvr_metric_value: 'L', numeric_value: '0.25'}])
        CvssMetringScorings.create([{metric_name: 'TargetDistribution', abrv_metric_name: 'TD', metric_value: 'Medium (26-75%)', abvr_metric_value: 'M', numeric_value: '0.75'}])
        CvssMetringScorings.create([{metric_name: 'TargetDistribution', abrv_metric_name: 'TD', metric_value: 'High (76-100%)', abvr_metric_value: 'H', numeric_value: '1'}])
